### ISSUE TITLE
에너미 시스템

### ISSUE THREAD

**Issue by Arkru1204** [Alliance-Of-School-Cafeteria/Stooge#6]
# Description
차후 공통적으로 적용할 에너미의 시스템을 구현
   
# Todo
- [x] HP, 피격 등을 담당 할 EnemyMain 구현
- [x] 이동을 담당 할 EnemyController 구현
- [x] NavMesh 컴포넌트 적용
   
# ETC
공통적으로 사용할 스크립트 작성, 이후 상속 받아 다른 개체에 적용
